// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[Table("InventoryLocation")]
public partial class InventoryLocation
{
    [Key]
    public int LocationID { get; set; }

    public int? WarehouseID { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string LocationCode { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public bool? isDeleted { get; set; }

    [InverseProperty("Location")]
    public virtual ICollection<InventoryRecord> InventoryRecords { get; set; } = new List<InventoryRecord>();

    [InverseProperty("FromLocation")]
    public virtual ICollection<InventoryTransaction> InventoryTransactionFromLocations { get; set; } = new List<InventoryTransaction>();

    [InverseProperty("ToLocation")]
    public virtual ICollection<InventoryTransaction> InventoryTransactionToLocations { get; set; } = new List<InventoryTransaction>();

    [ForeignKey("WarehouseID")]
    [InverseProperty("InventoryLocations")]
    public virtual Warehouse Warehouse { get; set; }
}