// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[Table("InventoryTransaction")]
public partial class InventoryTransaction
{
    [Key]
    public int TransactionID { get; set; }

    public int? ProductID { get; set; }

    public int? Quantity { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string TransactionType { get; set; }

    public int? FromLocationID { get; set; }

    public int? ToLocationID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TimeStamp { get; set; }

    [StringLength(128)]
    [ForeignKey("User")]
    [MaxLength(450)]

    public string UserID { get; set; }

    [Column(TypeName = "text")]
    public string Notes { get; set; }

    public bool? isDeleted { get; set; }

    [ForeignKey("FromLocationID")]
    [InverseProperty("InventoryTransactionFromLocations")]
    public virtual InventoryLocation FromLocation { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("InventoryTransactions")]
    public virtual Product Product { get; set; }

    [InverseProperty("OriginalTransaction")]
    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();

    [ForeignKey("ToLocationID")]
    [InverseProperty("InventoryTransactionToLocations")]
    public virtual InventoryLocation ToLocation { get; set; }
    public virtual ApplicationUser User { get; set; }
}