// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[PrimaryKey("ProductId", "LocationId")]
[Table("InventoryRecord")]
public partial class InventoryRecord
{
    [Key]
    public int ProductId { get; set; }

    [Key]
    public int LocationId { get; set; }

    public int? QuantityOnHand { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdated { get; set; }

    public bool? isDeleted { get; set; }

    [ForeignKey("LocationId")]
    [InverseProperty("InventoryRecords")]
    public virtual InventoryLocation Location { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("InventoryRecords")]
    public virtual Product Product { get; set; }
}