// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

public partial class MvcDbContextContext : DbContext
{
    public MvcDbContextContext()
    {
    }

    public MvcDbContextContext(DbContextOptions<MvcDbContextContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<InventoryLocation> InventoryLocations { get; set; }

    public virtual DbSet<InventoryRecord> InventoryRecords { get; set; }

    public virtual DbSet<InventoryTransaction> InventoryTransactions { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductHistory> ProductHistories { get; set; }

    public virtual DbSet<Return> Returns { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<Supplier_Product> Supplier_Products { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserLog> UserLogs { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<Warehouse> Warehouses { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=MvcDbContext;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryID).HasName("PK__Category__19093A2BB786D819");

            entity.Property(e => e.isDeleted).HasDefaultValue(false);

            entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory).HasConstraintName("FK_Category_ParentCategory");
        });

        modelBuilder.Entity<InventoryLocation>(entity =>
        {
            entity.HasKey(e => e.LocationID).HasName("PK__Inventor__E7FEA47761A8C86D");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.InventoryLocations).HasConstraintName("FK_InventoryLocation_Warehouse");
        });

        modelBuilder.Entity<InventoryRecord>(entity =>
        {
            entity.HasKey(e => new { e.ProductId, e.LocationId }).HasName("PK__Inventor__DA732C84073E7CF4");

            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Location).WithMany(p => p.InventoryRecords)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryRecord_Location");

            entity.HasOne(d => d.Product).WithMany(p => p.InventoryRecords)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryRecord_Product");
        });

        modelBuilder.Entity<InventoryTransaction>(entity =>
        {
            entity.HasKey(e => e.TransactionID).HasName("PK__Inventor__55433A4B621541E2");

            entity.Property(e => e.TimeStamp).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.FromLocation).WithMany(p => p.InventoryTransactionFromLocations).HasConstraintName("FK_InventoryTransaction_FromLocation");

            entity.HasOne(d => d.Product).WithMany(p => p.InventoryTransactions).HasConstraintName("FK_InventoryTransaction_Product");

            entity.HasOne(d => d.ToLocation).WithMany(p => p.InventoryTransactionToLocations).HasConstraintName("FK_InventoryTransaction_ToLocation");

            entity.HasOne(d => d.User).WithMany(p => p.InventoryTransactions).HasConstraintName("FK_InventoryTransaction_User");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Product__B40CC6CD934EF3CC");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Category).WithMany(p => p.Products).HasConstraintName("FK_Product_Category");
        });

        modelBuilder.Entity<ProductHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryID).HasName("PK__ProductH__4D7B4ADD8212BBA2");

            entity.Property(e => e.TimeStamp).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductHistories).HasConstraintName("FK_ProductHistory_Product");

            entity.HasOne(d => d.User).WithMany(p => p.ProductHistories).HasConstraintName("FK_ProductHistory_User");
        });

        modelBuilder.Entity<Return>(entity =>
        {
            entity.HasKey(e => e.ReturnID).HasName("PK__Return__F445E988A336DAC2");

            entity.Property(e => e.ReturnDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.OriginalTransaction).WithMany(p => p.Returns).HasConstraintName("FK_Return_InventoryTransaction");

            entity.HasOne(d => d.ProcessedByNavigation).WithMany(p => p.Returns).HasConstraintName("FK_Return_User");

            entity.HasOne(d => d.Product).WithMany(p => p.Returns).HasConstraintName("FK_Return_Product");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleID).HasName("PK__Role__8AFACE3A25328327");
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.HasKey(e => e.SupplierID).HasName("PK__Supplier__4BE66694917506C2");
        });

        modelBuilder.Entity<Supplier_Product>(entity =>
        {
            entity.HasKey(e => new { e.ProductId, e.SupplierID }).HasName("PK__Supplier__E0B2A0A4D4F6E1F3");

            entity.Property(e => e.LeadTimeDays).HasDefaultValue(0);

            entity.HasOne(d => d.Product).WithMany(p => p.Supplier_Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Supplier_Product_Product");

            entity.HasOne(d => d.Supplier).WithMany(p => p.Supplier_Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Supplier_Product_Supplier");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserID).HasName("PK__User__1788CCAC9A386F32");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserLog>(entity =>
        {
            entity.HasKey(e => e.LogID).HasName("PK__UserLog__5E5499A87D8F5FA5");

            entity.Property(e => e.TimeStamp).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.UserLogs).HasConstraintName("FK_UserLog_User");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserID, e.RoleID }).HasName("PK__UserRole__AF27604F413D0794");

            entity.Property(e => e.AssignedDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRole_Role");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRole_User");
        });

        modelBuilder.Entity<Warehouse>(entity =>
        {
            entity.HasKey(e => e.WarehouseID).HasName("PK__Warehous__2608AFD953877640");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}