// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[Table("ProductHistory")]
public partial class ProductHistory
{
    [Key]
    public int HistoryID { get; set; }

    public int? ProductID { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    public int? PreviousQuantity { get; set; }

    public int? NewQuantity { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Reason { get; set; }

    public int? ReferenceID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TimeStamp { get; set; }

    [StringLength(128)]
    public string UserID { get; set; }

    public bool? isDeleted { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("ProductHistories")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("ProductHistories")]
    public virtual User User { get; set; }
}