// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[Table("Product")]
public partial class Product
{
    [Key]
    public int ProductId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    public int? AvailableStock { get; set; }

    public int? CategoryId { get; set; }

    public int? CurrentQuantity { get; set; }

    public int? MinAvailableStock { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? UnitPrice { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? CostPrice { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Weight { get; set; }


    [Display(Name = "Image URL or Path")]
    public string ImageURL { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdated { get; set; }

    public bool? IsDeleted { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<InventoryRecord> InventoryRecords { get; set; } = new List<InventoryRecord>();

    [InverseProperty("Product")]
    public virtual ICollection<InventoryTransaction> InventoryTransactions { get; set; } = new List<InventoryTransaction>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductHistory> ProductHistories { get; set; } = new List<ProductHistory>();

    [InverseProperty("Product")]
    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();

    [InverseProperty("Product")]
    public virtual ICollection<Supplier_Product> Supplier_Products { get; set; } = new List<Supplier_Product>();
}