// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[Table("Return")]
public partial class Return
{
    [Key]
    public int ReturnID { get; set; }

    public int? OriginalTransactionID { get; set; }

    public int? ProductID { get; set; }

    public int? Quantity { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Reason { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Condition { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReturnDate { get; set; }

    [StringLength(128)]
    public string ProcessedBy { get; set; }

    [Column(TypeName = "text")]
    public string Notes { get; set; }

    public bool? isDeleted { get; set; }

    [ForeignKey("OriginalTransactionID")]
    [InverseProperty("Returns")]
    public virtual InventoryTransaction OriginalTransaction { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Returns")]
    public virtual Product Product { get; set; }
}