// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[PrimaryKey("ProductId", "SupplierID")]
[Table("Supplier_Product")]
public partial class Supplier_Product
{
    [Key]
    public int ProductId { get; set; }

    [Key]
    public int SupplierID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SupplierSKU { get; set; }

    public int? LeadTimeDays { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? UnitCost { get; set; }

    public bool? isDeleted { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Supplier_Products")]
    public virtual Product Product { get; set; }

    [ForeignKey("SupplierID")]
    [InverseProperty("Supplier_Products")]
    public virtual Supplier Supplier { get; set; }
}