// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[Table("Supplier")]
public partial class Supplier
{
    [Key]
    public int SupplierID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Company { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Column(TypeName = "text")]
    public string Address { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PaymentTerm { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "text")]
    public string Notes { get; set; }

    public bool? isDeleted { get; set; }

    [InverseProperty("Supplier")]
    public virtual ICollection<Supplier_Product> Supplier_Products { get; set; } = new List<Supplier_Product>();
}