// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[Table("UserLog")]
public partial class UserLog
{
    [Key]
    public int LogID { get; set; }

    [StringLength(128)]
    public string UserID { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ActionType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TimeStamp { get; set; }

    [Column(TypeName = "text")]
    public string AdditionalInfo { get; set; }
}