// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[PrimaryKey("UserID", "RoleID")]
[Table("UserRole")]
public partial class UserRole
{
    [Key]
    [StringLength(128)]
    public string UserID { get; set; }

    [Key]
    [StringLength(128)]
    public string RoleID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AssignedDate { get; set; }

    [ForeignKey("RoleID")]
    [InverseProperty("UserRoles")]
    public virtual Role Role { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("UserRoles")]
    public virtual User User { get; set; }
}