// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[Table("User")]
public partial class User
{
    [Key]
    [StringLength(128)]
    public string UserID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UserName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string FullName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLogin { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    public bool? isDeleted { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<InventoryTransaction> InventoryTransactions { get; set; } = new List<InventoryTransaction>();

    [InverseProperty("User")]
    public virtual ICollection<ProductHistory> ProductHistories { get; set; } = new List<ProductHistory>();

    [InverseProperty("ProcessedByNavigation")]
    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();

    [InverseProperty("User")]
    public virtual ICollection<UserLog> UserLogs { get; set; } = new List<UserLog>();

    [InverseProperty("User")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}