// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Warehouse_Management_System.Models;

[Table("Warehouse")]
public partial class Warehouse
{
    [Key]
    public int WarehouseID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "text")]
    public string Location { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ContactPhone { get; set; }

    public int? Capacity { get; set; }

    public bool? IsActive { get; set; }

    public bool? isDeleted { get; set; }

    [InverseProperty("Warehouse")]
    public virtual ICollection<InventoryLocation> InventoryLocations { get; set; } = new List<InventoryLocation>();
}